# Generated by Django 2.1.5 on 2019-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username')),
                ('user_password', models.CharField(max_length=20, verbose_name='Password')),
                ('user_nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('user_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=10, verbose_name='Gender')),
                ('user_createTime', models.DateField(auto_now_add=True, verbose_name='CreatTime')),
                ('user_email', models.CharField(max_length=20, verbose_name='Email')),
            ],
        ),
    ]
