# Generated by Django 2.1.7 on 2019-03-20 16:32

import LEHU.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_title', models.CharField(max_length=200)),
                ('activity_content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Full'), (4, 'Cancel')], default=1)),
                ('Category', models.IntegerField(choices=[(1, 'Card'), (2, 'Chess'), (3, 'BoardGames'), (4, 'Others')], default=1)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('numberofmem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of People')),
                ('budget', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=50)),
                ('Catagory', models.IntegerField(choices=[(1, 'Quit'), (2, 'Join'), (3, 'Modify'), (4, 'Close')], default=0)),
                ('Have_read', models.IntegerField(choices=[(1, 'Read'), (0, 'Unread')], default=0)),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='CreatTime')),
                ('Activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LEHU.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=20)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LEHU.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=15, null=True)),
                ('Picture', models.ImageField(upload_to=LEHU.models.store_picture_path)),
                ('website', models.CharField(max_length=30)),
                ('Popular_board_game', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username')),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nickname')),
                ('user_password', models.CharField(max_length=100, verbose_name='Password')),
                ('user_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=10, verbose_name='Gender')),
                ('user_createTime', models.DateField(auto_now_add=True, verbose_name='CreatTime')),
                ('user_email', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email')),
                ('user_province', models.CharField(blank=True, max_length=20, null=True, verbose_name='Province')),
                ('user_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('user_bio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bio')),
                ('user_favouritegame', models.CharField(blank=True, max_length=50, null=True, verbose_name='Favourite game')),
                ('user_cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell phone')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=LEHU.models.profile_picture_path)),
            ],
        ),
    ]
