# Generated by Django 2.1.5 on 2019-02-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='user/')),
            ],
        ),
    ]
