# Generated by Django 2.1.5 on 2019-02-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
