# Generated by Django 2.1.5 on 2019-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
