# Generated by Django 2.1.7 on 2019-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0002_auto_20190320_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='website',
            new_name='Website',
        ),
    ]
