# Generated by Django 2.1.5 on 2019-02-12 16:01

import LEHU.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0003_auto_20190211_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=LEHU.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
