# Generated by Django 2.1.7 on 2019-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0003_auto_20190320_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
