# Generated by Django 2.1.7 on 2019-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0004_store_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
