# Generated by Django 2.1.5 on 2019-02-12 16:09

import LEHU.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0004_auto_20190212_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=LEHU.models.profile_picture_path),
        ),
    ]
