# Generated by Django 2.1.5 on 2019-02-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0005_auto_20190212_1609'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='user',
#            name='user_nickname',
#            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nickname'),
#        ),
    ]
