# Generated by Django 2.1.7 on 2019-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0005_auto_20190320_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Activity_id',
            field=models.IntegerField(),
        ),
    ]
