# Generated by Django 2.1.5 on 2019-03-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0006_user_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_title', models.CharField(max_length=200)),
                ('activity_content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Full'), (4, 'Cancel')], default=1)),
                ('Category', models.IntegerField(choices=[(1, 'Card'), (2, 'Chess'), (3, 'BoardGames'), (4, 'Others')], default=1)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('numberofmem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of People')),
                ('budget', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
