# Generated by Django 2.1.7 on 2019-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0006_auto_20190325_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='Activity_id',
            field=models.IntegerField(blank=True),
        ),
    ]
