# Generated by Django 2.1.5 on 2019-03-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=20)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LEHU.Activity')),
            ],
        ),
    ]
