# Generated by Django 2.1.7 on 2019-03-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0008_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=50)),
                ('Activit_id', models.IntegerField()),
                ('Have_read', models.IntegerField(choices=[(1, 'Read'), (0, 'Unread')], default=0)),
                ('CreateTime', models.DateField(auto_now_add=True, verbose_name='CreatTime')),
            ],
        ),
    ]
