# Generated by Django 2.1.7 on 2019-03-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Activit_id',
            new_name='Activity_id',
        ),
    ]
