# Generated by Django 2.1.7 on 2019-03-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0010_auto_20190311_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Catagory',
            field=models.IntegerField(choices=[(1, 'Quit'), (2, 'Join'), (3, 'Modify'), (4, 'Close')], default=0),
        ),
    ]
