# Generated by Django 2.1.7 on 2019-03-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0011_message_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LEHU.Activity'),
        ),
    ]
