# Generated by Django 2.1.7 on 2019-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEHU', '0012_auto_20190312_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatTime'),
        ),
    ]
